import './globals.css';

import type { Metadata } from 'next';
import { Mulish } from 'next/font/google';
import { cookies } from 'next/headers';
import { ReactNode } from 'react';

import LocaleProvider from '@/commons/providers/LocaleProvider';

const main = Mulish({ subsets: ['latin', 'latin-ext'], variable: '--main-font' });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    const locale = (cookies().get('NEXT_LOCALE')?.value ?? 'pl') as 'pl' | 'en';
    return (
        <html
            className={main.variable}
            lang="en"
        >
            <body>
                <LocaleProvider locale={locale}>{children}</LocaleProvider>
            </body>
        </html>
    );
}
